---

build:doc:
  stage: .pre
  image: docker.io/blang/latex
  script:
    - cd doc/main
    - make
  artifacts:
    paths:
      - doc/main/documentation.pdf

build:verifierfrontend:
  stage: .pre
  image: izolight/rust-webpack
  script:
    - cd verifier/frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - verifier/static/files

build:signingserverfrontend:
  stage: .pre
  image: izolight/rust-webpack
  script:
    - cd src/frontend/rust-wasm-hashing
    - npm install
    - npm run build
  artifacts:
    paths:
      - src/frontend/rust-wasm-hashing/dist

build:signingserver:
  stage: .pre
  image: docker.io/maven:3.3-jdk-8
  script:
    - cp -v src/frontend/rust-wasm-hashing/dist/* signingserver/resources/static/.
    - cd signingserver
    - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
      - signingserver/target/signingserver-0.0.1-shaded.jar
  dependencies:
    - build:signingserverfrontend

build:verifier:
  stage: build
  image: golang:1.13-buster
  script:
    - cd verifier
    - go generate static/assets_generate.go
    - go generate config/assets_generate.go
  artifacts:
    paths:
      - verifier/static/assets_vfsdata.go
      - verifier/config/assets_vfsdata.go
  dependencies:
    - build:verifierfrontend

build:verifier:linux:
  stage: .post
  image: golang:1.13-buster
  script:
    - cd verifier
    - GOOS=linux GOARCH=amd64 go build -o verifier-linux-amd64 ./cmd/main.go
  artifacts:
    paths:
      - verifier/verifier-linux-amd64
  dependencies:
    - build:verifier

build:verifier:mac:
  stage: .post
  image: golang:1.13-buster
  script:
    - cd verifier
    - GOOS=darwin GOARCH=amd64 go build -o verifier-darwin-amd64 ./cmd/main.go
  artifacts:
    paths:
      - verifier/verifier-darwin-amd64
  dependencies:
    - build:verifier

build:verifier:windows:
  stage: .post
  image: golang:1.13-buster
  script:
    - cd verifier
    - GOOS=windows GOARCH=amd64 go build -o verifier-windows-amd64.exe ./cmd/main.go
  artifacts:
    paths:
      - verifier/verifier-windows-amd64.exe
  dependencies:
    - build:verifier
